insert into `schools` ( `short_code`, `name`, `area_code`, `area_name`, `address`, `lat`, `lon`, `sort`) values ( 'shsjysxy', '上海视觉艺术学院', '021', '上海', null, null, null, '7');


insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'学术交流类','文学社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'学术交流类','PS社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'学术交流类','粤语社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'学术交流类','筑梦社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','枫剧社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','涂鸦社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','英语社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','陶艺社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','摄影社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','环境社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','视觉出品');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','手绘社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','公益社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','创意社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','云间学社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','设计汇');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','刀画社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','D乘社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'公益实践类','辩论社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'文化艺术类','恋物社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'文化艺术类','动漫社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'文化艺术类','茶艺社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'文化艺术类','书法社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'文化艺术类','桌游社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'文化艺术类','器乐社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'文化艺术类','曲艺社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'文化艺术类','音乐社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'文化艺术类','西墨书法社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','滑板社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','网球社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','宗道会');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','乒乓球社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','高尔夫社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','轮滑社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','街舞社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','剑道社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','滑冰社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','跆拳道');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','松涛会');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','瑜伽社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','羽毛球社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','健美操社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','真格拳社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','排球社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','台球社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','足球社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','舞蹈社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','骑行社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','游泳社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','田径社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','篮球社');
insert into groups(school_id,school_name,category_id,category_name,name) values(7,'上海视觉艺术学院',0,'体育健身类','弓箭社');

update groups set category_id=1 where category_name='体育健身类';
update groups set category_id=2 where category_name='学术交流类';
update groups set category_id=3 where category_name='文化艺术类';
update groups set category_id=4 where category_name='公益实践类';